// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewOffer struct {
	Title         string `json:"title"`
	Location      string `json:"location"`
	Description   string `json:"description"`
	TitleImageURL string `json:"titleImageUrl"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Offer struct {
	ID            string `json:"id"`
	Title         string `json:"title"`
	Location      string `json:"location"`
	Description   string `json:"description"`
	TitleImageURL string `json:"titleImageUrl"`
	User          *User  `json:"user"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
