name: default
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35

      - name: build
        run: make build

      - name: container
        run: make container

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push to dockerhub
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: make container-push
